### ISSUE TITLE
Runit and OpenRC can't run concurrently because of conflicting services from default services

### ISSUE THREAD

**Issue by konimex** [artix-linux/runit-artix#3]
Since PR #2 is merged, I noticed that *both* OpenRC and runit calls `agetty-tty` (runit calls them from `/etc/runit/2` while OpenRC calls them from runlevel `default` which is called by runit in `/etc/runit/1`), this is problematic because conflicting service means 2 getty running concurrently, and I had to remove OpenRC because of this.

- Possible solutions:
  - Remove `default` from the runlevels started by OpenRC in stage 1. (Personally I don't like this one)
  - Add an option (preferably in `/etc/runit/rc.conf`) checking if OpenRC is installed *and* if the user wants to run OpenRC concurrently with runit. (Now on #4)

**Comment by konimex** [comment]
Actually, if possible, I think #2 should be reverted.

From [Gentoo Wiki](https://wiki.gentoo.org/wiki/Runit#OpenRC.27s_runit_integration_feature):

>OpenRC does not integrate as expected when runit is used as the init system, since there will be two runsvdir processes: the one supervised by runit with /etc/service or /var/service as the scan directory, and the unsupervised one launched by OpenRC with /run/openrc/sv as the scan directory. So the result will be two independent supervision trees.

**Comment by cromerc** [comment]
That wiki info does not apply in this case. That is only if runit is the init and is the supervisor for the service. In this case the supervisor is not runit, it is the supervisor that comes with openrc.

This is really a temporary solution to lack of runit service scripts, ideally this wouldn't be needed if we had enough runit service scripts for all our packages.

I would like to revert that commit, but only once we have the necessary service scripts for  runit available. The idea behind this is to allow openrc to handle things until runit has matured enough under artix.

I do prefer your approach of using a config option in rc.conf. I will merge this soon after the holidays when I get back to my computer.
